image: gitpod/workspace-full

tasks:
  - init: |
      # Update pip & setuptools
      pip3 install --upgrade pip setuptools
      # Installiere PlatformIO CLI in ~/.local/bin
      pip3 install --user platformio

  # PlatformIO direkt über absoluten Pfad ausführen
  - command: ~/.local/bin/pio run

ports:
  - port: 8000
    onOpen: ignore
